version: "3"
services:
  server:
    image: kien-go-todos
    container_name: "kien-go-todos"
    build: ./
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    restart: on-failure
  postgresql:
    image: postgres:13
    container_name: postgres_container_go
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-location}
      - POSTGRES_USER=${POSTGRES_USER:-merlin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-@merlin123}
    ports:
      - "5432:5432"
    restart: unless-stopped
